language: node_js
node_js:
  # - "7" # Coming soon once https://github.com/jugglingdb/sqlite3-adapter/pull/39 is merged.
  - "6"

env:
  - NODE_ENV=test GITHUB_TOKEN=phony

script:
  - time npm run coverage

sudo: required

services:
  - docker

# After tests ran successfully, build docker container.
after_success:
  - docker build -t rgausnet/backstroke:latest .
  - ./provision.sh "one"
