language: node_js
node_js:
  # - "7" # Coming soon once https://github.com/jugglingdb/sqlite3-adapter/pull/39 is merged.
  - "6"

env:
  - NODE_ENV=test GITHUB_TOKEN=phony

script:
  - time npm test

# After tests ran successfully, build docker container.
after_success:
  - echo
