version: '2'
services:

  backstroke-server:
    build: ./backend
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      GITHUB_CALLBACK_URL: "${GITHUB_CALLBACK_URL}"
      SESSION_SECRET: "${SESSION_SECRET}"
    ports:
      - "8001:8000"

  backstroke-client:
    build: ./frontend
    ports:
      - "8002:80"

  mongodb:
    image: mongo:3.0
    #volumes:
      #- "/data:/data/db"

  haproxy:
    image: haproxy:1.4-alpine
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
    links:
      - backstroke-server
      - backstroke-client
    ports:
      - "8000:80"
